In [1]:
import os
os.environ["PYTHONUTF8"] = "1"

In [190]:

from datasets import Dataset
from transformers import AutoTokenizer, AutoModelForCausalLM
from peft import LoraConfig, get_peft_model
from trl import SFTTrainer, SFTConfig

In [191]:
import torch
if torch.cuda.is_available():
    device = torch.device("cuda")
else:
    device = torch.device("cpu")
print(f"Using device: {device}")

Using device: cuda

In [192]:
model_id = "HuggingFaceTB/SmolLM2-135M-Instruct"

tokenizer = AutoTokenizer.from_pretrained(model_id)
model = AutoModelForCausalLM.from_pretrained(model_id)
model = model.to(device)

print("Model parameters (total):", sum(p.numel() for p in model.parameters()))

Model parameters (total): 134515008

In [193]:
ALL_WORDS = [
    "idea", "glow", "rust", "maze", "echo", "wisp", "veto", "lush", "gaze", "knit", "fume", "plow",
    "void", "oath", "grim", "crisp", "lunar", "fable", "quest", "verge", "brawn", "elude", "aisle",
    "ember", "crave", "ivory", "mirth", "knack", "wryly", "onset", "mosaic", "velvet", "sphinx",
    "radius", "summit", "banner", "cipher", "glisten", "mantle", "scarab", "expose", "fathom",
    "tavern", "fusion", "relish", "lantern", "enchant", "torrent", "capture", "orchard", "eclipse",
    "frescos", "triumph", "absolve", "gossipy", "prelude", "whistle", "resolve", "zealous",
    "mirage", "aperture", "sapphire",
]

In [194]:
def generate_records():
    for word in ALL_WORDS:
        yield {
            "prompt": (
                f"You spell words with hyphens between the letters like this W-O-R-D.\nWord:\n{word}\n\n"
                + "Spelling:\n"
            ),
            "completion": "-".join(word).upper() + ".",  # Of the form W-O-R-D.
        }


ds = Dataset.from_generator(generate_records)
ds[0]

{'prompt': 'You spell words with hyphens between the letters like this W-O-R-D.\nWord:\nidea\n\nSpelling:\n',
 'completion': 'I-D-E-A.'}

In [195]:
ds = ds.train_test_split(test_size=0.25, seed=42)

In [196]:
ds

DatasetDict({
    train: Dataset({
        features: ['prompt', 'completion'],
        num_rows: 46
    })
    test: Dataset({
        features: ['prompt', 'completion'],
        num_rows: 16
    })
})

In [197]:
train_ds = ds["train"]
test_ds = ds["test"]

print(len(train_ds))
print(len(test_ds))

46
16

# base

In [198]:
def check_spelling(
    model, tokenizer, prompt: str, actual_spelling: str, max_new_tokens: int = 20
):
    inputs = tokenizer(prompt,return_tensors="pt").to(device)
    gen_out = model.generate(**inputs,max_new_tokens=max_new_tokens,use_cache=False)
    decoded_out = tokenizer.decode(gen_out[0],skip_special_tokens=True)
    proposed_spelling = decoded_out.split("Spelling:")[-1].strip().split("\n")[0].strip()
    actual_spelling = actual_spelling.strip()
    chars_correct = sum(1 for a, b in zip(actual_spelling, proposed_spelling) if a == b)
    num_correct = 1 if actual_spelling == proposed_spelling else 0

    print(
        f"Proposed: {proposed_spelling} | Actual: {actual_spelling} "
        f"| Matches: {'YES' if proposed_spelling == actual_spelling else 'NO'}"
    )

    return chars_correct / len(actual_spelling) , num_correct

In [199]:
print(ds["test"][0]["completion"])
check_spelling(
    model=model,
    tokenizer=tokenizer,
    prompt=ds["test"][0]["prompt"],
    actual_spelling=ds["test"][0]["completion"],
)

W-R-Y-L-Y.
Proposed: wry | Actual: W-R-Y-L-Y. | Matches: NO

(0.0, 0)

In [200]:
print(ds["train"][0])

{'prompt': 'You spell words with hyphens between the letters like this W-O-R-D.\nWord:\nsphinx\n\nSpelling:\n', 'completion': 'S-P-H-I-N-X.'}

# Base model Accuracy

In [201]:
correct = 0.0
correct_chars = 0.0
for example in ds["train"]:
    prompt = example["prompt"]
    completion = example["completion"]
    result = check_spelling(
        model=model,
        tokenizer=tokenizer,
        prompt=prompt,
        actual_spelling=completion,
        max_new_tokens=20,
    )
    correct += result[1]
    correct_chars+= result[0]

print(f"{correct}/{len(ds['train'])} words correct\n {correct_chars}/{len(ds['train'])} characters in words correct")

Proposed: sphinx | Actual: S-P-H-I-N-X. | Matches: NO
Proposed: brawn | Actual: B-R-A-W-N. | Matches: NO
Proposed: goss | Actual: G-O-S-S-I-P-Y. | Matches: NO
Proposed: enchant | Actual: E-N-C-H-A-N-T. | Matches: NO
Proposed: tavern | Actual: T-A-V-E-R-N. | Matches: NO
Proposed: whistle | Actual: W-H-I-S-T-L-E. | Matches: NO
Proposed: W-O-R-D | Actual: C-A-P-T-U-R-E. | Matches: NO
Proposed: echo | Actual: E-C-H-O. | Matches: NO
Proposed: mirth | Actual: M-I-R-T-H. | Matches: NO
Proposed: cris | Actual: C-R-I-S-P. | Matches: NO
Proposed: zeal | Actual: Z-E-A-L-O-U-S. | Matches: NO
Proposed:  | Actual: E-M-B-E-R. | Matches: NO
Proposed: scarab | Actual: S-C-A-R-A-B. | Matches: NO
Proposed:  | Actual: K-N-I-T. | Matches: NO
Proposed: resolve | Actual: R-E-S-O-L-V-E. | Matches: NO
Proposed: velvet | Actual: V-E-L-V-E-T. | Matches: NO
Proposed:  | Actual: A-B-S-O-L-V-E. | Matches: NO
Proposed: lunar | Actual: L-U-N-A-R. | Matches: NO
Proposed: maze | Actual: M-A-Z-E. | Matches: NO
Proposed:  | Actual: S-U-M-M-I-T. | Matches: NO
Proposed: mosaic | Actual: M-O-S-A-I-C. | Matches: NO
Proposed: fume | Actual: F-U-M-E. | Matches: NO
Proposed: e- | Actual: E-C-L-I-P-S-E. | Matches: NO
Proposed: prel | Actual: P-R-E-L-U-D-E. | Matches: NO
Proposed: veto | Actual: V-E-T-O. | Matches: NO
Proposed: mantle | Actual: M-A-N-T-L-E. | Matches: NO
Proposed: plow | Actual: P-L-O-W. | Matches: NO
Proposed: relish | Actual: R-E-L-I-S-H. | Matches: NO
Proposed: fathom | Actual: F-A-T-H-O-M. | Matches: NO
Proposed: aisle | Actual: A-I-S-L-E. | Matches: NO
Proposed: W-O-R-D | Actual: V-E-R-G-E. | Matches: NO
Proposed: - B-N-O-B-N-A-R-D | Actual: B-A-N-N-E-R. | Matches: NO
Proposed:  | Actual: I-D-E-A. | Matches: NO
Proposed: torrent | Actual: T-O-R-R-E-N-T. | Matches: NO
Proposed: orchard | Actual: O-R-C-H-A-R-D. | Matches: NO
Proposed: lantern | Actual: L-A-N-T-E-R-N. | Matches: NO
Proposed:  | Actual: V-O-I-D. | Matches: NO
Proposed: fusion | Actual: F-U-S-I-O-N. | Matches: NO
Proposed:  | Actual: G-R-I-M. | Matches: NO
Proposed: apert | Actual: A-P-E-R-T-U-R-E. | Matches: NO
Proposed:  | Actual: R-U-S-T. | Matches: NO
Proposed: cipher | Actual: C-I-P-H-E-R. | Matches: NO
Proposed:  | Actual: R-A-D-I-U-S. | Matches: NO
Proposed: glow | Actual: G-L-O-W. | Matches: NO
Proposed: oath | Actual: O-A-T-H. | Matches: NO
Proposed: gaze | Actual: G-A-Z-E. | Matches: NO
0.0/46 words correct
 1.1023809523809525/46 characters in words correct

# Lets try SFT with LORA

In [202]:
trainable = sum(p.numel() for p in model.parameters() if p.requires_grad)
total = sum(p.numel() for p in model.parameters())
print(
    f"Trainable params BEFORE: {trainable:,} / {total:,} ({100 * trainable / total:.2f}%)"
)

Trainable params BEFORE: 134,515,008 / 134,515,008 (100.00%)

In [203]:
lora_config = LoraConfig(
    r=64,
    lora_alpha=8,
    lora_dropout=0.4,
    bias="none",
    task_type="CAUSAL_LM",
)
model = get_peft_model(model, lora_config)

In [204]:
trainable = sum(p.numel() for p in model.parameters() if p.requires_grad)
total = sum(p.numel() for p in model.parameters())
print(
    f"Trainable params AFTER: {trainable:,} / {total:,} ({100 * trainable / total:.2f}%)"
)

Trainable params AFTER: 3,686,400 / 138,201,408 (2.67%)

In [205]:
?SFTConfig

Init signature:
SFTConfig(
    output_dir: Optional[str] = None,
    overwrite_output_dir: bool = False,
    do_train: bool = False,
    do_eval: bool = False,
    do_predict: bool = False,
    eval_strategy: Union[transformers.trainer_utils.IntervalStrategy, str] = 'no',
    prediction_loss_only: bool = False,
    per_device_train_batch_size: int = 8,
    per_device_eval_batch_size: int = 8,
    per_gpu_train_batch_size: Optional[int] = None,
    per_gpu_eval_batch_size: Optional[int] = None,
    gradient_accumulation_steps: int = 1,
    eval_accumulation_steps: Optional[int] = None,
    eval_delay: Optional[float] = 0,
    torch_empty_cache_steps: Optional[int] = None,
    learning_rate: float = 2e-05,
    weight_decay: float = 0.0,
    adam_beta1: float = 0.9,
    adam_beta2: float = 0.999,
    adam_epsilon: float = 1e-08,
    max_grad_norm: float = 1.0,
    num_train_epochs: float = 3.0,
    max_steps: int = -1,
    lr_scheduler_type: Union[transformers.trainer_utils.SchedulerType, str] = 'linear',
    lr_scheduler_kwargs: Union[dict, str, NoneType] = <factory>,
    warmup_ratio: float = 0.0,
    warmup_steps: int = 0,
    log_level: Optional[str] = 'passive',
    log_level_replica: Optional[str] = 'warning',
    log_on_each_node: bool = True,
    logging_dir: Optional[str] = None,
    logging_strategy: Union[transformers.trainer_utils.IntervalStrategy, str] = 'steps',
    logging_first_step: bool = False,
    logging_steps: float = 500,
    logging_nan_inf_filter: bool = True,
    save_strategy: Union[transformers.trainer_utils.SaveStrategy, str] = 'steps',
    save_steps: float = 500,
    save_total_limit: Optional[int] = None,
    save_safetensors: Optional[bool] = True,
    save_on_each_node: bool = False,
    save_only_model: bool = False,
    restore_callback_states_from_checkpoint: bool = False,
    no_cuda: bool = False,
    use_cpu: bool = False,
    use_mps_device: bool = False,
    seed: int = 42,
    data_seed: Optional[int] = None,
    jit_mode_eval: bool = False,
    use_ipex: bool = False,
    bf16: bool = False,
    fp16: bool = False,
    fp16_opt_level: str = 'O1',
    half_precision_backend: str = 'auto',
    bf16_full_eval: bool = False,
    fp16_full_eval: bool = False,
    tf32: Optional[bool] = None,
    local_rank: int = -1,
    ddp_backend: Optional[str] = None,
    tpu_num_cores: Optional[int] = None,
    tpu_metrics_debug: bool = False,
    debug: Union[str, list[transformers.debug_utils.DebugOption]] = '',
    dataloader_drop_last: bool = False,
    eval_steps: Optional[float] = None,
    dataloader_num_workers: int = 0,
    dataloader_prefetch_factor: Optional[int] = None,
    past_index: int = -1,
    run_name: Optional[str] = None,
    disable_tqdm: Optional[bool] = None,
    remove_unused_columns: Optional[bool] = True,
    label_names: Optional[list[str]] = None,
    load_best_model_at_end: Optional[bool] = False,
    metric_for_best_model: Optional[str] = None,
    greater_is_better: Optional[bool] = None,
    ignore_data_skip: bool = False,
    fsdp: Union[list[transformers.trainer_utils.FSDPOption], str, NoneType] = '',
    fsdp_min_num_params: int = 0,
    fsdp_config: Union[dict, str, NoneType] = None,
    tp_size: Optional[int] = 0,
    fsdp_transformer_layer_cls_to_wrap: Optional[str] = None,
    accelerator_config: Union[dict, str, NoneType] = None,
    deepspeed: Union[dict, str, NoneType] = None,
    label_smoothing_factor: float = 0.0,
    optim: Union[transformers.training_args.OptimizerNames, str] = 'adamw_torch',
    optim_args: Optional[str] = None,
    adafactor: bool = False,
    group_by_length: bool = False,
    length_column_name: Optional[str] = 'length',
    report_to: Union[NoneType, str, list[str]] = None,
    ddp_find_unused_parameters: Optional[bool] = None,
    ddp_bucket_cap_mb: Optional[int] = None,
    ddp_broadcast_buffers: Optional[bool] = None,
    dataloader_pin_memory: bool = True,
    dataloader_persistent_workers: bool = False,
    skip_memory_metrics: bool = True,
    use_legacy_prediction_loop: bool = False,
    push_to_hub: bool = False,
    resume_from_checkpoint: Optional[str] = None,
    hub_model_id: Optional[str] = None,
    hub_strategy: Union[transformers.trainer_utils.HubStrategy, str] = 'every_save',
    hub_token: Optional[str] = None,
    hub_private_repo: Optional[bool] = None,
    hub_always_push: bool = False,
    gradient_checkpointing: bool = False,
    gradient_checkpointing_kwargs: Union[dict, str, NoneType] = None,
    include_inputs_for_metrics: bool = False,
    include_for_metrics: list[str] = <factory>,
    eval_do_concat_batches: bool = True,
    fp16_backend: str = 'auto',
    push_to_hub_model_id: Optional[str] = None,
    push_to_hub_organization: Optional[str] = None,
    push_to_hub_token: Optional[str] = None,
    mp_parameters: str = '',
    auto_find_batch_size: bool = False,
    full_determinism: bool = False,
    torchdynamo: Optional[str] = None,
    ray_scope: Optional[str] = 'last',
    ddp_timeout: Optional[int] = 1800,
    torch_compile: bool = False,
    torch_compile_backend: Optional[str] = None,
    torch_compile_mode: Optional[str] = None,
    include_tokens_per_second: Optional[bool] = False,
    include_num_input_tokens_seen: Optional[bool] = False,
    neftune_noise_alpha: Optional[float] = None,
    optim_target_modules: Union[NoneType, str, list[str]] = None,
    batch_eval_metrics: bool = False,
    eval_on_start: bool = False,
    use_liger_kernel: Optional[bool] = False,
    eval_use_gather_object: Optional[bool] = False,
    average_tokens_across_devices: Optional[bool] = False,
    model_init_kwargs: Optional[dict[str, Any]] = None,
    dataset_text_field: str = 'text',
    dataset_kwargs: Optional[dict[str, Any]] = None,
    dataset_num_proc: Optional[int] = None,
    eos_token: Optional[str] = None,
    pad_token: Optional[str] = None,
    max_length: Optional[int] = 1024,
    packing: bool = False,
    padding_free: bool = False,
    eval_packing: Optional[bool] = None,
    completion_only_loss: Optional[bool] = None,
    dataset_batch_size: Optional[int] = None,
    num_of_sequences: Optional[int] = None,
    chars_per_token: Optional[float] = None,
    max_seq_length: Optional[int] = None,
    use_liger: Optional[bool] = None,
) -> None
Docstring:
Configuration class for the [`SFTTrainer`].

Only the parameters specific to SFT training are listed here. For details on other parameters, refer to the
[`~transformers.TrainingArguments`] documentation.

Using [`~transformers.HfArgumentParser`] we can turn this class into
[argparse](https://docs.python.org/3/library/argparse#module-argparse) arguments that can be specified on the
command line.

Parameters:
    > Parameters that control the model

    model_init_kwargs (`dict[str, Any]` or `None`, *optional*, defaults to `None`):
        Keyword arguments for [`~transformers.AutoModelForCausalLM.from_pretrained`], used when the `model`
        argument of the [`SFTTrainer`] is provided as a string.

    > Parameters that control the data preprocessing

    dataset_text_field (`str`, *optional*, defaults to `"text"`):
        Name of the column that contains text data in the dataset.
    dataset_kwargs (`dict[str, Any]` or `None`, *optional*, defaults to `None`):
        Dictionary of optional keyword arguments for the dataset preparation. The only supported key is
        `skip_prepare_dataset`.
    dataset_num_proc (`int` or `None`, *optional*, defaults to `None`):
        Number of processes to use for processing the dataset.
    eos_token (`str` or `None`, *optional*, defaults to `None`):
        Token used to indicate the end of a turn or sequence. If `None`, it defaults to `processing_class.eos_token`.
    pad_token (`int` or `None`, *optional*, defaults to `None`):
        Token used for padding. If `None`, it defaults to `processing_class.pad_token`, or if that is also `None`,
        it falls back to `processing_class.eos_token`.
    max_length (`int` or `None`, *optional*, defaults to `1024`):
        Maximum length of the tokenized sequence. Sequences longer than `max_length` are truncated from the right.
        If `None`, no truncation is applied. When packing is enabled, this value sets the sequence length.
    packing (`bool`, *optional*, defaults to `False`):
        Whether to pack multiple sequences into a fixed-length format. Uses `max_length` to define sequence length.
    padding_free (`bool`, *optional*, defaults to `False`):
        Whether to perform forward passes without padding by flattening all sequences in the batch into a single
        continuous sequence. This reduces memory usage by eliminating padding overhead. Currently, this is only
        supported with the `flash_attention_2` attention implementation, which can efficiently handle the flattened
        batch structure.
    eval_packing (`bool` or `None`, *optional*, defaults to `None`):
        Whether to pack the eval dataset. If `None`, uses the same value as `packing`.

    > Parameters that control the training

    learning_rate (`float`, *optional*, defaults to `2e-5`):
        Initial learning rate for [`AdamW`] optimizer. The default value replaces that of
        [`~transformers.TrainingArguments`].
    completion_only_loss (`bool` or `None`, *optional*, defaults to `None`):
        Whether to compute loss only on the completion part of the sequence. If set to `True`, loss is computed
        only on the completion, which is supported only for [prompt-completion](#prompt-completion) datasets. If
        `False`, loss is computed on the entire sequence. If `None` (default), the behavior depends on the dataset:
        loss is computed on the completion for [prompt-completion](#prompt-completion) datasets, and on
        the full sequence for [language modeling](#language-modeling) datasets.
File:           d:\_self_masters\_udacity_masters\env_python\pytorch_env\lib\site-packages\trl\trainer\sft_config.py
Type:           type
Subclasses:

In [206]:
from transformers.trainer_utils import SchedulerType
print(SchedulerType._member_names_)

['LINEAR', 'COSINE', 'COSINE_WITH_RESTARTS', 'POLYNOMIAL', 'CONSTANT', 'CONSTANT_WITH_WARMUP', 'INVERSE_SQRT', 'REDUCE_ON_PLATEAU', 'COSINE_WITH_MIN_LR', 'WARMUP_STABLE_DECAY']

In [224]:
output_dir = "tensorboard"
training_args = SFTConfig(
    output_dir=output_dir,
    per_device_train_batch_size=8,
    per_device_eval_batch_size=8,
    gradient_accumulation_steps=2,
    num_train_epochs=100,
    learning_rate=5e-5,
    logging_steps=8,
    eval_strategy="steps",
    eval_steps=8,
    save_strategy="no",
    fp16=False,
    lr_scheduler_type="reduce_lr_on_plateau",
)

In [225]:
trainer = SFTTrainer(
    model=model,
    train_dataset=ds["train"],
    eval_dataset=ds["test"],
    args=training_args,
)

No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.

In [226]:
trainer.train()

TrainOutput(global_step=300, training_loss=0.6888021926085154, metrics={'train_runtime': 141.7332, 'train_samples_per_second': 32.455, 'train_steps_per_second': 2.117, 'total_flos': 141777694414080.0, 'train_loss': 0.6888021926085154})

Check Accuracy with SFT

In [227]:
def test(ds_tag='train'):
    correct = 0.0
    correct_chars = 0.0
    for example in ds[ds_tag]:
        prompt = example["prompt"]
        completion = example["completion"]
        result = check_spelling(
            model=model,
            tokenizer=tokenizer,
            prompt=prompt,
            actual_spelling=completion,
            max_new_tokens=20,
        )
        correct += result[1]
        correct_chars+= result[0]

    print(f"{correct}/{len(ds['train'])} words correct\n {correct_chars}/{len(ds['train'])} characters in words correct")

In [228]:
test('train')

Proposed: S-P-H-I-N-K-I-A. | Actual: S-P-H-I-N-X. | Matches: NO
Proposed: B-R-A-N-Y. | Actual: B-R-A-W-N. | Matches: NO
Proposed: G-O-S-H-O-P-I-Y. | Actual: G-O-S-S-I-P-Y. | Matches: NO
Proposed: E-N-C-H-A-N-T. | Actual: E-N-C-H-A-N-T. | Matches: YES
Proposed: T-A-A-N-B-E. | Actual: T-A-V-E-R-N. | Matches: NO
Proposed: W-H-I-S-E. | Actual: W-H-I-S-T-L-E. | Matches: NO
Proposed: C-U-P-A-R-I-N. | Actual: C-A-P-T-U-R-E. | Matches: NO
Proposed: E-C-H-O-R-E. | Actual: E-C-H-O. | Matches: NO
Proposed: M-I-T-H. | Actual: M-I-R-T-H. | Matches: NO
Proposed: C-R-I-S-P. | Actual: C-R-I-S-P. | Matches: YES
Proposed: Z-E-A-L-O-S. | Actual: Z-E-A-L-O-U-S. | Matches: NO
Proposed: E-M-U-R-E. | Actual: E-M-B-E-R. | Matches: NO
Proposed: S-A-C-R-A-B. | Actual: S-C-A-R-A-B. | Matches: NO
Proposed: W-I-N-T. | Actual: K-N-I-T. | Matches: NO
Proposed: R-E-S-I-L-E. | Actual: R-E-S-O-L-V-E. | Matches: NO
Proposed: V-E-L-V-T. | Actual: V-E-L-V-E-T. | Matches: NO
Proposed: A-B-E-U-R-E. | Actual: A-B-S-O-L-V-E. | Matches: NO
Proposed: L-U-R-A-N. | Actual: L-U-N-A-R. | Matches: NO
Proposed: M-A-S-E-A. | Actual: M-A-Z-E. | Matches: NO
Proposed: S-U-M-T-I-N. | Actual: S-U-M-M-I-T. | Matches: NO
Proposed: M-A-S-I-T-O. | Actual: M-O-S-A-I-C. | Matches: NO
Proposed: F-U-M-E. | Actual: F-U-M-E. | Matches: YES
Proposed: E-C-L-O-S-E. | Actual: E-C-L-I-P-S-E. | Matches: NO
Proposed: P-E-R-L-O-N. | Actual: P-R-E-L-U-D-E. | Matches: NO
Proposed: V-E-T-O. | Actual: V-E-T-O. | Matches: YES
Proposed: M-A-T-L-E-R. | Actual: M-A-N-T-L-E. | Matches: NO
Proposed: P-L-O-W. | Actual: P-L-O-W. | Matches: YES
Proposed: R-E-L-S-I-R-L. | Actual: R-E-L-I-S-H. | Matches: NO
Proposed: F-A-M-T. | Actual: F-A-T-H-O-M. | Matches: NO
Proposed: A-I-S-L-E. | Actual: A-I-S-L-E. | Matches: YES
Proposed: V-E-R-G-E. | Actual: V-E-R-G-E. | Matches: YES
Proposed: B-N-A-B-N-O-R. | Actual: B-A-N-N-E-R. | Matches: NO
Proposed: I-D-E-A-R-O-D. | Actual: I-D-E-A. | Matches: NO
Proposed: T-O-R-A-T. | Actual: T-O-R-R-E-N-T. | Matches: NO
Proposed: O-R-H-D-E. | Actual: O-R-C-H-A-R-D. | Matches: NO
Proposed: L-A-N-T-I-N. | Actual: L-A-N-T-E-R-N. | Matches: NO
Proposed: V-O-T. | Actual: V-O-I-D. | Matches: NO
Proposed: F-U-S-R-E-A-L. | Actual: F-U-S-I-O-N. | Matches: NO
Proposed: G-R-M-O-N. | Actual: G-R-I-M. | Matches: NO
Proposed: A-P-R-E-T-U-R-E. | Actual: A-P-E-R-T-U-R-E. | Matches: NO
Proposed: R-T-O-R-D. | Actual: R-U-S-T. | Matches: NO
Proposed: C-I-F-E-R-S. | Actual: C-I-P-H-E-R. | Matches: NO
Proposed: R-A-S-I-N-D. | Actual: R-A-D-I-U-S. | Matches: NO
Proposed: G-L-O-V-H. | Actual: G-L-O-W. | Matches: NO
Proposed: O-A-H-T. | Actual: O-A-T-H. | Matches: NO
Proposed: G-A-Z-E-R. | Actual: G-A-Z-E. | Matches: NO
7.0/46 words correct
 33.06190476190477/46 characters in words correct

In [229]:
test('test')

Proposed: W-R-Y-I-L-Y. | Actual: W-R-Y-L-Y. | Matches: NO
Proposed: G-L-I-N-E-S. | Actual: G-L-I-S-T-E-N. | Matches: NO
Proposed: C-A-S-E-L. | Actual: Q-U-E-S-T. | Matches: NO
Proposed: C-E-R-E-V-E. | Actual: C-R-A-V-E. | Matches: NO
Proposed: L-U-S-I-S-H. | Actual: L-U-S-H. | Matches: NO
Proposed: F-A-L-I-C-E. | Actual: F-A-B-L-E. | Matches: NO
Proposed: K-N-A-R-K. | Actual: K-N-A-C-K. | Matches: NO
Proposed: T-I-R-U-M-P-H-I-L-E. | Actual: T-R-I-U-M-P-H. | Matches: NO
Proposed: S-A-P-I-C-R-I-A. | Actual: S-A-P-P-H-I-R-E. | Matches: NO
Proposed: E-X-P-S-E-R. | Actual: E-X-P-O-S-E. | Matches: NO
Proposed: F-S-R-O-C-S. | Actual: F-R-E-S-C-O-S. | Matches: NO
Proposed: W-E-P-I-S-H. | Actual: W-I-S-P. | Matches: NO
Proposed: M-I-R-E-G-A. | Actual: M-I-R-A-G-E. | Matches: NO
Proposed: I-V-O-Y-U-R-E. | Actual: I-V-O-R-Y. | Matches: NO
Proposed: O-N-S-H-E-R-D. | Actual: O-N-S-E-T. | Matches: NO
Proposed: E-L-E-U-A-D. | Actual: E-L-U-D-E. | Matches: NO
0.0/46 words correct
 10.577976190476189/46 characters in words correct

# So only 0 out of all words were correct

I will revisit this once I learn a bit more , i think i will checkout HF's transformer course

# GRPO

In [230]:
def debug_reward(*args, **kwargs):
    print("\n===== REWARD DEBUG =====")

    print("args:", len(args))

    for i, arg in enumerate(args):
        print(f"\narg[{i}] type =", type(arg))

        if isinstance(arg, list) and len(arg) > 0:
            print("first element:", arg[0])
            print(len(arg))
            print(arg)
        

    print("\nkwargs keys:", kwargs.keys())

    for k, v in kwargs.items():
        print(f"\n{k}:")
        print("type =", type(v))

        if isinstance(v, list) and len(v) > 0:
            print("first element =", v[0])
            print(len(v))
            print(v)

    raise Exception("STOP AFTER DEBUG")

In [231]:
def proportion_correct(word, proposed_spelling):
    correct_spelling = "-".join(word).upper()

    score = 0.0

    max_len = max(len(correct_spelling), len(proposed_spelling))
    proposed_spelling_padded = proposed_spelling.ljust(max_len, " ")
    correct_spelling_padded = correct_spelling.ljust(max_len, " ")

    for a, b in zip(correct_spelling_padded, proposed_spelling_padded):
        if a == b:
            score += 1
        else:
            score -= 1

    return score / (
        len(correct_spelling)
    )

In [232]:
assert proportion_correct("hello", "H-E-L-L-O") == 1
assert proportion_correct("hello", "H-E-L-") == 3 / 9
assert proportion_correct("hello", "H-E-L-L-O!") == 8 / 9

In [233]:
import numpy as np

import re

def reward_spelling(prompts, completions, **kwargs):

    rewards = []
    #print(prompts)
    #print(completions)
    
    for prompt, completion in zip(prompts, completions):

        word = (
            prompt
            .split("Word:\n")[1]
            .split("\n\nSpelling:")[0]
            .strip()
        )
        generated = completion.strip()

        reward = proportion_correct(
            word,
            generated
        )

        rewards.append(reward)
    print(f"Spelling Reward mean and std: {np.mean(rewards):.3f} +/- {np.std(rewards):.3f}")
    return rewards

In [234]:
import re
import numpy as np

def reward_response_in_form_of_letter_dash_letter(
    prompts,
    completions,
    **kwargs
):
    """
    Rewards outputs that look like:
    W-O-R-D
    """

    pattern = re.compile(r"^([A-Z]-)*[A-Z]\.?$")

    completion_strings = [
        completion.split("\n")[0].strip().upper()
        for completion in completions
    ]

    rewards = [
        1.0 if pattern.fullmatch(c) else 0.0
        for c in completion_strings
    ]

    print(
        f"Letter-dash-letter rewards mean/std: "
        f"{np.mean(rewards):.3f} +/- {np.std(rewards):.3f}"
    )

    return rewards

In [235]:
assert reward_response_in_form_of_letter_dash_letter(
    completions=[
        "H-E-L-L-O",
        "hello",
        "H-i!",
    ],
    prompts=[]
) == [1, 0, 0]

Letter-dash-letter rewards mean/std: 0.333 +/- 0.471

In [236]:
from trl import GRPOConfig, GRPOTrainer

In [237]:
training_args = GRPOConfig(
    output_dir="data/spelling-grpo",
    max_completion_length=20,
    logging_steps=5,
    learning_rate=1e-5,
    num_train_epochs=20, 
    per_device_train_batch_size=8,
    num_generations=4,  
    lr_scheduler_type="cosine",
    beta=0.0,
)

In [238]:
trainer = GRPOTrainer(
    model=model,
    reward_funcs=[
        reward_spelling,
        reward_response_in_form_of_letter_dash_letter
    ],
    args=training_args,
    train_dataset=ds["train"],
)

No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.

In [239]:
trainer.train()

Spelling Reward mean and std: 0.250 +/- 0.203
Letter-dash-letter rewards mean/std: 1.000 +/- 0.000

Spelling Reward mean and std: 0.252 +/- 0.258
Letter-dash-letter rewards mean/std: 1.000 +/- 0.000
Spelling Reward mean and std: 0.291 +/- 0.265
Letter-dash-letter rewards mean/std: 0.875 +/- 0.331
Spelling Reward mean and std: 0.424 +/- 0.452
Letter-dash-letter rewards mean/std: 1.000 +/- 0.000
Spelling Reward mean and std: 0.286 +/- 0.286
Letter-dash-letter rewards mean/std: 1.000 +/- 0.000
Spelling Reward mean and std: 0.024 +/- 0.453
Letter-dash-letter rewards mean/std: 0.750 +/- 0.433
Spelling Reward mean and std: -0.045 +/- 0.187
Letter-dash-letter rewards mean/std: 1.000 +/- 0.000
Spelling Reward mean and std: 0.131 +/- 0.233
Letter-dash-letter rewards mean/std: 1.000 +/- 0.000
Spelling Reward mean and std: 0.339 +/- 0.404
Letter-dash-letter rewards mean/std: 1.000 +/- 0.000
Spelling Reward mean and std: 0.154 +/- 0.350
Letter-dash-letter rewards mean/std: 1.000 +/- 0.000
Spelling Reward mean and std: 0.412 +/- 0.259
Letter-dash-letter rewards mean/std: 1.000 +/- 0.000
Spelling Reward mean and std: 0.106 +/- 0.252
Letter-dash-letter rewards mean/std: 1.000 +/- 0.000
Spelling Reward mean and std: 0.143 +/- 0.452
Letter-dash-letter rewards mean/std: 1.000 +/- 0.000
Spelling Reward mean and std: -0.097 +/- 0.470
Letter-dash-letter rewards mean/std: 1.000 +/- 0.000
Spelling Reward mean and std: 0.578 +/- 0.286
Letter-dash-letter rewards mean/std: 0.750 +/- 0.433
Spelling Reward mean and std: -0.061 +/- 0.132
Letter-dash-letter rewards mean/std: 1.000 +/- 0.000
Spelling Reward mean and std: 0.300 +/- 0.252
Letter-dash-letter rewards mean/std: 1.000 +/- 0.000
Spelling Reward mean and std: 0.113 +/- 0.448
Letter-dash-letter rewards mean/std: 0.750 +/- 0.433
Spelling Reward mean and std: 0.318 +/- 0.253
Letter-dash-letter rewards mean/std: 1.000 +/- 0.000
Spelling Reward mean and std: 0.059 +/- 0.452
Letter-dash-letter rewards mean/std: 1.000 +/- 0.000
Spelling Reward mean and std: -0.019 +/- 0.304
Letter-dash-letter rewards mean/std: 1.000 +/- 0.000
Spelling Reward mean and std: 0.230 +/- 0.421
Letter-dash-letter rewards mean/std: 0.875 +/- 0.331
Spelling Reward mean and std: 0.120 +/- 0.456
Letter-dash-letter rewards mean/std: 0.875 +/- 0.331
Spelling Reward mean and std: 0.357 +/- 0.510
Letter-dash-letter rewards mean/std: 1.000 +/- 0.000
Spelling Reward mean and std: 0.214 +/- 0.303
Letter-dash-letter rewards mean/std: 1.000 +/- 0.000
Spelling Reward mean and std: 0.331 +/- 0.421
Letter-dash-letter rewards mean/std: 0.875 +/- 0.331
Spelling Reward mean and std: 0.288 +/- 0.179
Letter-dash-letter rewards mean/std: 0.875 +/- 0.331
Spelling Reward mean and std: 0.273 +/- 0.144
Letter-dash-letter rewards mean/std: 1.000 +/- 0.000
Spelling Reward mean and std: 0.182 +/- 0.419
Letter-dash-letter rewards mean/std: 1.000 +/- 0.000
Spelling Reward mean and std: 0.327 +/- 0.275
Letter-dash-letter rewards mean/std: 1.000 +/- 0.000
Spelling Reward mean and std: 0.213 +/- 0.405
Letter-dash-letter rewards mean/std: 1.000 +/- 0.000
Spelling Reward mean and std: 0.048 +/- 0.144
Letter-dash-letter rewards mean/std: 1.000 +/- 0.000
Spelling Reward mean and std: 0.278 +/- 0.330
Letter-dash-letter rewards mean/std: 1.000 +/- 0.000
Spelling Reward mean and std: -0.173 +/- 0.901
Letter-dash-letter rewards mean/std: 0.875 +/- 0.331
Spelling Reward mean and std: -0.068 +/- 0.599
Letter-dash-letter rewards mean/std: 0.750 +/- 0.433
Spelling Reward mean and std: 0.182 +/- 0.252
Letter-dash-letter rewards mean/std: 1.000 +/- 0.000
Spelling Reward mean and std: 0.449 +/- 0.253
Letter-dash-letter rewards mean/std: 0.875 +/- 0.331
Spelling Reward mean and std: -0.821 +/- 1.986
Letter-dash-letter rewards mean/std: 0.750 +/- 0.433
Spelling Reward mean and std: 0.168 +/- 0.285
Letter-dash-letter rewards mean/std: 1.000 +/- 0.000
Spelling Reward mean and std: -0.412 +/- 0.522
Letter-dash-letter rewards mean/std: 0.625 +/- 0.484
Spelling Reward mean and std: 0.054 +/- 0.901
Letter-dash-letter rewards mean/std: 0.875 +/- 0.331
Spelling Reward mean and std: -0.054 +/- 0.296
Letter-dash-letter rewards mean/std: 0.750 +/- 0.433
Spelling Reward mean and std: 0.165 +/- 0.461
Letter-dash-letter rewards mean/std: 1.000 +/- 0.000
Spelling Reward mean and std: -0.031 +/- 0.113
Letter-dash-letter rewards mean/std: 1.000 +/- 0.000
Spelling Reward mean and std: 0.307 +/- 0.163
Letter-dash-letter rewards mean/std: 1.000 +/- 0.000
Spelling Reward mean and std: 0.420 +/- 0.276
Letter-dash-letter rewards mean/std: 1.000 +/- 0.000
Spelling Reward mean and std: -0.045 +/- 0.443
Letter-dash-letter rewards mean/std: 0.875 +/- 0.331
Spelling Reward mean and std: 0.165 +/- 0.172
Letter-dash-letter rewards mean/std: 1.000 +/- 0.000
Spelling Reward mean and std: 0.110 +/- 0.329
Letter-dash-letter rewards mean/std: 1.000 +/- 0.000
Spelling Reward mean and std: 0.153 +/- 0.308
Letter-dash-letter rewards mean/std: 1.000 +/- 0.000
Spelling Reward mean and std: 0.045 +/- 0.312
Letter-dash-letter rewards mean/std: 0.875 +/- 0.331
Spelling Reward mean and std: 0.319 +/- 0.536
Letter-dash-letter rewards mean/std: 0.875 +/- 0.331
Spelling Reward mean and std: -0.609 +/- 1.482
Letter-dash-letter rewards mean/std: 0.750 +/- 0.433
Spelling Reward mean and std: 0.365 +/- 0.333
Letter-dash-letter rewards mean/std: 0.875 +/- 0.331
Spelling Reward mean and std: 0.240 +/- 0.343
Letter-dash-letter rewards mean/std: 0.875 +/- 0.331
Spelling Reward mean and std: 0.048 +/- 0.144
Letter-dash-letter rewards mean/std: 1.000 +/- 0.000
Spelling Reward mean and std: 0.323 +/- 0.313
Letter-dash-letter rewards mean/std: 0.875 +/- 0.331
Spelling Reward mean and std: 0.471 +/- 0.337
Letter-dash-letter rewards mean/std: 1.000 +/- 0.000
Spelling Reward mean and std: 0.179 +/- 0.376
Letter-dash-letter rewards mean/std: 1.000 +/- 0.000
Spelling Reward mean and std: 0.003 +/- 0.258
Letter-dash-letter rewards mean/std: 0.875 +/- 0.331
Spelling Reward mean and std: 0.161 +/- 0.263
Letter-dash-letter rewards mean/std: 1.000 +/- 0.000
Spelling Reward mean and std: -0.821 +/- 2.023
Letter-dash-letter rewards mean/std: 0.875 +/- 0.331
Spelling Reward mean and std: 0.333 +/- 0.379
Letter-dash-letter rewards mean/std: 1.000 +/- 0.000
Spelling Reward mean and std: 0.260 +/- 0.479
Letter-dash-letter rewards mean/std: 0.875 +/- 0.331
Spelling Reward mean and std: 0.123 +/- 0.225
Letter-dash-letter rewards mean/std: 1.000 +/- 0.000
Spelling Reward mean and std: 0.102 +/- 0.212
Letter-dash-letter rewards mean/std: 1.000 +/- 0.000
Spelling Reward mean and std: 0.164 +/- 0.278
Letter-dash-letter rewards mean/std: 1.000 +/- 0.000
Spelling Reward mean and std: 0.172 +/- 0.347
Letter-dash-letter rewards mean/std: 1.000 +/- 0.000
Spelling Reward mean and std: 0.094 +/- 0.336
Letter-dash-letter rewards mean/std: 0.750 +/- 0.433
Spelling Reward mean and std: 0.373 +/- 0.276
Letter-dash-letter rewards mean/std: 1.000 +/- 0.000
Spelling Reward mean and std: 0.252 +/- 0.334
Letter-dash-letter rewards mean/std: 1.000 +/- 0.000
Spelling Reward mean and std: 0.304 +/- 0.419
Letter-dash-letter rewards mean/std: 1.000 +/- 0.000
Spelling Reward mean and std: -0.065 +/- 0.241
Letter-dash-letter rewards mean/std: 0.875 +/- 0.331
Spelling Reward mean and std: 0.298 +/- 0.207
Letter-dash-letter rewards mean/std: 1.000 +/- 0.000
Spelling Reward mean and std: -0.802 +/- 2.222
Letter-dash-letter rewards mean/std: 0.875 +/- 0.331
Spelling Reward mean and std: 0.029 +/- 0.124
Letter-dash-letter rewards mean/std: 1.000 +/- 0.000
Spelling Reward mean and std: 0.575 +/- 0.388
Letter-dash-letter rewards mean/std: 1.000 +/- 0.000
Spelling Reward mean and std: 0.308 +/- 0.377
Letter-dash-letter rewards mean/std: 1.000 +/- 0.000
Spelling Reward mean and std: 0.062 +/- 0.444
Letter-dash-letter rewards mean/std: 1.000 +/- 0.000
Spelling Reward mean and std: -0.023 +/- 0.232
Letter-dash-letter rewards mean/std: 0.875 +/- 0.331
Spelling Reward mean and std: 0.190 +/- 0.325
Letter-dash-letter rewards mean/std: 1.000 +/- 0.000
Spelling Reward mean and std: 0.464 +/- 0.283
Letter-dash-letter rewards mean/std: 1.000 +/- 0.000
Spelling Reward mean and std: 0.359 +/- 0.446
Letter-dash-letter rewards mean/std: 1.000 +/- 0.000
Spelling Reward mean and std: -0.215 +/- 1.290
Letter-dash-letter rewards mean/std: 0.875 +/- 0.331
Spelling Reward mean and std: 0.096 +/- 0.491
Letter-dash-letter rewards mean/std: 0.750 +/- 0.433
Spelling Reward mean and std: -0.104 +/- 0.386
Letter-dash-letter rewards mean/std: 0.875 +/- 0.331
Spelling Reward mean and std: 0.196 +/- 0.119
Letter-dash-letter rewards mean/std: 1.000 +/- 0.000
Spelling Reward mean and std: 0.136 +/- 0.404
Letter-dash-letter rewards mean/std: 1.000 +/- 0.000
Spelling Reward mean and std: 0.159 +/- 0.168
Letter-dash-letter rewards mean/std: 1.000 +/- 0.000
Spelling Reward mean and std: 0.358 +/- 0.308
Letter-dash-letter rewards mean/std: 1.000 +/- 0.000
Spelling Reward mean and std: 0.228 +/- 0.191
Letter-dash-letter rewards mean/std: 1.000 +/- 0.000
Spelling Reward mean and std: 0.057 +/- 0.284
Letter-dash-letter rewards mean/std: 0.875 +/- 0.331
Spelling Reward mean and std: 0.077 +/- 0.154
Letter-dash-letter rewards mean/std: 1.000 +/- 0.000
Spelling Reward mean and std: 0.357 +/- 0.243
Letter-dash-letter rewards mean/std: 1.000 +/- 0.000
Spelling Reward mean and std: 0.290 +/- 0.374
Letter-dash-letter rewards mean/std: 0.875 +/- 0.331
Spelling Reward mean and std: -0.019 +/- 0.120
Letter-dash-letter rewards mean/std: 1.000 +/- 0.000
Spelling Reward mean and std: 0.238 +/- 0.254
Letter-dash-letter rewards mean/std: 1.000 +/- 0.000
Spelling Reward mean and std: 0.244 +/- 0.355
Letter-dash-letter rewards mean/std: 1.000 +/- 0.000
Spelling Reward mean and std: 0.304 +/- 0.271
Letter-dash-letter rewards mean/std: 1.000 +/- 0.000
Spelling Reward mean and std: 0.358 +/- 0.370
Letter-dash-letter rewards mean/std: 1.000 +/- 0.000
Spelling Reward mean and std: 0.250 +/- 0.113
Letter-dash-letter rewards mean/std: 1.000 +/- 0.000
Spelling Reward mean and std: 0.268 +/- 0.352
Letter-dash-letter rewards mean/std: 0.875 +/- 0.331
Spelling Reward mean and std: 0.470 +/- 0.412
Letter-dash-letter rewards mean/std: 1.000 +/- 0.000
Spelling Reward mean and std: 0.323 +/- 0.322
Letter-dash-letter rewards mean/std: 1.000 +/- 0.000
Spelling Reward mean and std: 0.045 +/- 0.111
Letter-dash-letter rewards mean/std: 1.000 +/- 0.000
Spelling Reward mean and std: 0.256 +/- 0.384
Letter-dash-letter rewards mean/std: 0.875 +/- 0.331
Spelling Reward mean and std: 0.259 +/- 0.450
Letter-dash-letter rewards mean/std: 1.000 +/- 0.000
Spelling Reward mean and std: 0.398 +/- 0.388
Letter-dash-letter rewards mean/std: 1.000 +/- 0.000
Spelling Reward mean and std: 0.014 +/- 0.187
Letter-dash-letter rewards mean/std: 1.000 +/- 0.000
Spelling Reward mean and std: 0.221 +/- 0.165
Letter-dash-letter rewards mean/std: 1.000 +/- 0.000
Spelling Reward mean and std: 0.367 +/- 0.255
Letter-dash-letter rewards mean/std: 1.000 +/- 0.000
Spelling Reward mean and std: 0.187 +/- 0.314
Letter-dash-letter rewards mean/std: 0.875 +/- 0.331
Spelling Reward mean and std: 0.278 +/- 0.388
Letter-dash-letter rewards mean/std: 1.000 +/- 0.000
Spelling Reward mean and std: 0.341 +/- 0.429
Letter-dash-letter rewards mean/std: 1.000 +/- 0.000
Spelling Reward mean and std: 0.112 +/- 0.459
Letter-dash-letter rewards mean/std: 1.000 +/- 0.000
Spelling Reward mean and std: 0.159 +/- 0.188
Letter-dash-letter rewards mean/std: 1.000 +/- 0.000
Spelling Reward mean and std: 0.318 +/- 0.227
Letter-dash-letter rewards mean/std: 1.000 +/- 0.000
Spelling Reward mean and std: 0.395 +/- 0.257
Letter-dash-letter rewards mean/std: 1.000 +/- 0.000
Spelling Reward mean and std: 0.232 +/- 0.262
Letter-dash-letter rewards mean/std: 1.000 +/- 0.000
Spelling Reward mean and std: 0.260 +/- 0.412
Letter-dash-letter rewards mean/std: 0.875 +/- 0.331
Spelling Reward mean and std: 0.190 +/- 0.406
Letter-dash-letter rewards mean/std: 0.875 +/- 0.331
Spelling Reward mean and std: 0.172 +/- 0.323
Letter-dash-letter rewards mean/std: 1.000 +/- 0.000
Spelling Reward mean and std: 0.047 +/- 0.443
Letter-dash-letter rewards mean/std: 0.750 +/- 0.433
Spelling Reward mean and std: 0.136 +/- 0.310
Letter-dash-letter rewards mean/std: 1.000 +/- 0.000
Spelling Reward mean and std: 0.190 +/- 0.259
Letter-dash-letter rewards mean/std: 0.875 +/- 0.331
Spelling Reward mean and std: 0.330 +/- 0.163
Letter-dash-letter rewards mean/std: 1.000 +/- 0.000
Spelling Reward mean and std: 0.172 +/- 0.326
Letter-dash-letter rewards mean/std: 1.000 +/- 0.000
Spelling Reward mean and std: -0.719 +/- 2.160
Letter-dash-letter rewards mean/std: 1.000 +/- 0.000
Spelling Reward mean and std: 0.500 +/- 0.371
Letter-dash-letter rewards mean/std: 1.000 +/- 0.000
Spelling Reward mean and std: 0.365 +/- 0.282
Letter-dash-letter rewards mean/std: 1.000 +/- 0.000
Spelling Reward mean and std: 0.161 +/- 0.315
Letter-dash-letter rewards mean/std: 1.000 +/- 0.000
Spelling Reward mean and std: 0.081 +/- 0.361
Letter-dash-letter rewards mean/std: 0.875 +/- 0.331
Spelling Reward mean and std: 0.377 +/- 0.205
Letter-dash-letter rewards mean/std: 1.000 +/- 0.000
Spelling Reward mean and std: 0.396 +/- 0.589
Letter-dash-letter rewards mean/std: 0.750 +/- 0.433
Spelling Reward mean and std: -0.011 +/- 0.433
Letter-dash-letter rewards mean/std: 1.000 +/- 0.000
Spelling Reward mean and std: -0.231 +/- 0.819
Letter-dash-letter rewards mean/std: 0.875 +/- 0.331
Spelling Reward mean and std: 0.150 +/- 0.204
Letter-dash-letter rewards mean/std: 1.000 +/- 0.000
Spelling Reward mean and std: 0.000 +/- 0.271
Letter-dash-letter rewards mean/std: 1.000 +/- 0.000
Spelling Reward mean and std: 0.327 +/- 0.227
Letter-dash-letter rewards mean/std: 1.000 +/- 0.000
Spelling Reward mean and std: 0.119 +/- 0.375
Letter-dash-letter rewards mean/std: 0.750 +/- 0.433
Spelling Reward mean and std: 0.525 +/- 0.379
Letter-dash-letter rewards mean/std: 1.000 +/- 0.000
Spelling Reward mean and std: 0.321 +/- 0.292
Letter-dash-letter rewards mean/std: 1.000 +/- 0.000
Spelling Reward mean and std: 0.567 +/- 0.242
Letter-dash-letter rewards mean/std: 1.000 +/- 0.000
Spelling Reward mean and std: 0.181 +/- 0.146
Letter-dash-letter rewards mean/std: 1.000 +/- 0.000
Spelling Reward mean and std: 0.132 +/- 0.116
Letter-dash-letter rewards mean/std: 1.000 +/- 0.000
Spelling Reward mean and std: -0.048 +/- 0.415
Letter-dash-letter rewards mean/std: 0.875 +/- 0.331
Spelling Reward mean and std: 0.107 +/- 0.341
Letter-dash-letter rewards mean/std: 1.000 +/- 0.000
Spelling Reward mean and std: 0.103 +/- 0.200
Letter-dash-letter rewards mean/std: 1.000 +/- 0.000
Spelling Reward mean and std: 0.008 +/- 0.393
Letter-dash-letter rewards mean/std: 0.875 +/- 0.331
Spelling Reward mean and std: 0.288 +/- 0.279
Letter-dash-letter rewards mean/std: 1.000 +/- 0.000
Spelling Reward mean and std: 0.643 +/- 0.398
Letter-dash-letter rewards mean/std: 1.000 +/- 0.000
Spelling Reward mean and std: 0.164 +/- 0.241
Letter-dash-letter rewards mean/std: 1.000 +/- 0.000
Spelling Reward mean and std: -0.083 +/- 0.436
Letter-dash-letter rewards mean/std: 1.000 +/- 0.000
Spelling Reward mean and std: 0.096 +/- 0.199
Letter-dash-letter rewards mean/std: 1.000 +/- 0.000
Spelling Reward mean and std: -0.687 +/- 2.245
Letter-dash-letter rewards mean/std: 1.000 +/- 0.000
Spelling Reward mean and std: 0.386 +/- 0.410
Letter-dash-letter rewards mean/std: 1.000 +/- 0.000
Spelling Reward mean and std: 0.188 +/- 0.178
Letter-dash-letter rewards mean/std: 1.000 +/- 0.000
Spelling Reward mean and std: 0.420 +/- 0.249
Letter-dash-letter rewards mean/std: 1.000 +/- 0.000
Spelling Reward mean and std: 0.140 +/- 0.205
Letter-dash-letter rewards mean/std: 1.000 +/- 0.000
Spelling Reward mean and std: 0.408 +/- 0.460
Letter-dash-letter rewards mean/std: 1.000 +/- 0.000
Spelling Reward mean and std: 0.225 +/- 0.471
Letter-dash-letter rewards mean/std: 1.000 +/- 0.000
Spelling Reward mean and std: -0.010 +/- 0.250
Letter-dash-letter rewards mean/std: 0.750 +/- 0.433
Spelling Reward mean and std: 0.141 +/- 0.237
Letter-dash-letter rewards mean/std: 1.000 +/- 0.000
Spelling Reward mean and std: 0.098 +/- 0.139
Letter-dash-letter rewards mean/std: 1.000 +/- 0.000
Spelling Reward mean and std: 0.260 +/- 0.328
Letter-dash-letter rewards mean/std: 1.000 +/- 0.000
Spelling Reward mean and std: 0.268 +/- 0.372
Letter-dash-letter rewards mean/std: 1.000 +/- 0.000
Spelling Reward mean and std: 0.251 +/- 0.343
Letter-dash-letter rewards mean/std: 0.875 +/- 0.331
Spelling Reward mean and std: -0.167 +/- 0.479
Letter-dash-letter rewards mean/std: 0.750 +/- 0.433
Spelling Reward mean and std: 0.226 +/- 0.425
Letter-dash-letter rewards mean/std: 0.875 +/- 0.331
Spelling Reward mean and std: 0.087 +/- 0.201
Letter-dash-letter rewards mean/std: 1.000 +/- 0.000
Spelling Reward mean and std: -0.250 +/- 0.292
Letter-dash-letter rewards mean/std: 1.000 +/- 0.000
Spelling Reward mean and std: 0.494 +/- 0.334
Letter-dash-letter rewards mean/std: 1.000 +/- 0.000
Spelling Reward mean and std: 0.265 +/- 0.280
Letter-dash-letter rewards mean/std: 0.875 +/- 0.331
Spelling Reward mean and std: 0.075 +/- 0.237
Letter-dash-letter rewards mean/std: 1.000 +/- 0.000
Spelling Reward mean and std: 0.179 +/- 0.309
Letter-dash-letter rewards mean/std: 1.000 +/- 0.000
Spelling Reward mean and std: 0.198 +/- 0.325
Letter-dash-letter rewards mean/std: 0.875 +/- 0.331
Spelling Reward mean and std: 0.679 +/- 0.245
Letter-dash-letter rewards mean/std: 1.000 +/- 0.000
Spelling Reward mean and std: 0.268 +/- 0.299
Letter-dash-letter rewards mean/std: 1.000 +/- 0.000
Spelling Reward mean and std: 0.101 +/- 0.163
Letter-dash-letter rewards mean/std: 1.000 +/- 0.000
Spelling Reward mean and std: 0.450 +/- 0.229
Letter-dash-letter rewards mean/std: 1.000 +/- 0.000
Spelling Reward mean and std: -0.517 +/- 1.747
Letter-dash-letter rewards mean/std: 0.875 +/- 0.331
Spelling Reward mean and std: 0.240 +/- 0.330
Letter-dash-letter rewards mean/std: 1.000 +/- 0.000
Spelling Reward mean and std: 0.135 +/- 0.475
Letter-dash-letter rewards mean/std: 0.875 +/- 0.331
Spelling Reward mean and std: 0.224 +/- 0.215
Letter-dash-letter rewards mean/std: 1.000 +/- 0.000
Spelling Reward mean and std: 0.232 +/- 0.333
Letter-dash-letter rewards mean/std: 0.875 +/- 0.331
Spelling Reward mean and std: 0.153 +/- 0.237
Letter-dash-letter rewards mean/std: 1.000 +/- 0.000
Spelling Reward mean and std: 0.125 +/- 0.346
Letter-dash-letter rewards mean/std: 1.000 +/- 0.000
Spelling Reward mean and std: -0.050 +/- 0.537
Letter-dash-letter rewards mean/std: 0.875 +/- 0.331
Spelling Reward mean and std: 0.093 +/- 0.194
Letter-dash-letter rewards mean/std: 1.000 +/- 0.000
Spelling Reward mean and std: 0.394 +/- 0.392
Letter-dash-letter rewards mean/std: 1.000 +/- 0.000
Spelling Reward mean and std: 0.339 +/- 0.265
Letter-dash-letter rewards mean/std: 1.000 +/- 0.000
Spelling Reward mean and std: 0.289 +/- 0.279
Letter-dash-letter rewards mean/std: 1.000 +/- 0.000
Spelling Reward mean and std: 0.255 +/- 0.245
Letter-dash-letter rewards mean/std: 1.000 +/- 0.000
Spelling Reward mean and std: 0.361 +/- 0.346
Letter-dash-letter rewards mean/std: 1.000 +/- 0.000
Spelling Reward mean and std: 0.379 +/- 0.340
Letter-dash-letter rewards mean/std: 1.000 +/- 0.000
Spelling Reward mean and std: 0.326 +/- 0.547
Letter-dash-letter rewards mean/std: 1.000 +/- 0.000
Spelling Reward mean and std: 0.321 +/- 0.462
Letter-dash-letter rewards mean/std: 1.000 +/- 0.000
Spelling Reward mean and std: 0.062 +/- 0.420
Letter-dash-letter rewards mean/std: 1.000 +/- 0.000
Spelling Reward mean and std: 0.295 +/- 0.248
Letter-dash-letter rewards mean/std: 1.000 +/- 0.000
Spelling Reward mean and std: -0.121 +/- 0.314
Letter-dash-letter rewards mean/std: 0.875 +/- 0.331
Spelling Reward mean and std: 0.320 +/- 0.282
Letter-dash-letter rewards mean/std: 1.000 +/- 0.000
Spelling Reward mean and std: 0.246 +/- 0.387
Letter-dash-letter rewards mean/std: 0.875 +/- 0.331
Spelling Reward mean and std: -0.077 +/- 0.656

TrainOutput(global_step=460, training_loss=0.0066804468672236675, metrics={'train_runtime': 751.9714, 'train_samples_per_second': 1.223, 'train_steps_per_second': 0.612, 'total_flos': 0.0, 'train_loss': 0.0066804468672236675})

In [242]:
test('train')

Proposed: S-P-H-I-N-X. | Actual: S-P-H-I-N-X. | Matches: YES
Proposed: B-R-A-N-Y. | Actual: B-R-A-W-N. | Matches: NO
Proposed: G-O-S-H-O-P-I-Y. | Actual: G-O-S-S-I-P-Y. | Matches: NO
Proposed: E-N-C-H-A-N-T. | Actual: E-N-C-H-A-N-T. | Matches: YES
Proposed: T-A-A-N-B. | Actual: T-A-V-E-R-N. | Matches: NO
Proposed: W-H-I-S-E. | Actual: W-H-I-S-T-L-E. | Matches: NO
Proposed: C-U-P-A-R-I-N. | Actual: C-A-P-T-U-R-E. | Matches: NO
Proposed: E-C-H-O-R-E. | Actual: E-C-H-O. | Matches: NO
Proposed: M-I-T-H. | Actual: M-I-R-T-H. | Matches: NO
Proposed: C-R-I-S-P. | Actual: C-R-I-S-P. | Matches: YES
Proposed: Z-E-A-L-O-S. | Actual: Z-E-A-L-O-U-S. | Matches: NO
Proposed: E-M-B-U-R. | Actual: E-M-B-E-R. | Matches: NO
Proposed: S-A-C-R-A-B. | Actual: S-C-A-R-A-B. | Matches: NO
Proposed: W-I-N-T. | Actual: K-N-I-T. | Matches: NO
Proposed: R-E-S-I-L-E. | Actual: R-E-S-O-L-V-E. | Matches: NO
Proposed: V-E-L-V-T. | Actual: V-E-L-V-E-T. | Matches: NO
Proposed: A-B-E-U-R-E. | Actual: A-B-S-O-L-V-E. | Matches: NO
Proposed: L-U-R-A-N. | Actual: L-U-N-A-R. | Matches: NO
Proposed: M-A-S-E-A. | Actual: M-A-Z-E. | Matches: NO
Proposed: S-U-M-T-I-N. | Actual: S-U-M-M-I-T. | Matches: NO
Proposed: M-A-S-I-T-O. | Actual: M-O-S-A-I-C. | Matches: NO
Proposed: F-U-M-E. | Actual: F-U-M-E. | Matches: YES
Proposed: E-C-L-O-S-E. | Actual: E-C-L-I-P-S-E. | Matches: NO
Proposed: P-E-R-L-E-D. | Actual: P-R-E-L-U-D-E. | Matches: NO
Proposed: V-E-T-O. | Actual: V-E-T-O. | Matches: YES
Proposed: M-A-T-L-E. | Actual: M-A-N-T-L-E. | Matches: NO
Proposed: P-L-O-W. | Actual: P-L-O-W. | Matches: YES
Proposed: R-E-L-S-I-R. | Actual: R-E-L-I-S-H. | Matches: NO
Proposed: F-A-M-T. | Actual: F-A-T-H-O-M. | Matches: NO
Proposed: A-I-S-E-L-E. | Actual: A-I-S-L-E. | Matches: NO
Proposed: V-E-R-G-E. | Actual: V-E-R-G-E. | Matches: YES
Proposed: B-N-A-B-N-E. | Actual: B-A-N-N-E-R. | Matches: NO
Proposed: I-D-E-A. | Actual: I-D-E-A. | Matches: YES
Proposed: T-O-R-A-N. | Actual: T-O-R-R-E-N-T. | Matches: NO
Proposed: O-R-H-D-E. | Actual: O-R-C-H-A-R-D. | Matches: NO
Proposed: L-A-N-T-I-N. | Actual: L-A-N-T-E-R-N. | Matches: NO
Proposed: V-O-T. | Actual: V-O-I-D. | Matches: NO
Proposed: F-U-S-R-E. | Actual: F-U-S-I-O-N. | Matches: NO
Proposed: G-R-M. | Actual: G-R-I-M. | Matches: NO
Proposed: A-P-R-E-T-U-R-E. | Actual: A-P-E-R-T-U-R-E. | Matches: NO
Proposed: R-T-O-R. | Actual: R-U-S-T. | Matches: NO
Proposed: C-I-F-E-R. | Actual: C-I-P-H-E-R. | Matches: NO
Proposed: R-A-S-I-N-D. | Actual: R-A-D-I-U-S. | Matches: NO
Proposed: G-L-O-V-H. | Actual: G-L-O-W. | Matches: NO
Proposed: O-A-H-T. | Actual: O-A-T-H. | Matches: NO
Proposed: G-A-Z-E. | Actual: G-A-Z-E. | Matches: YES
9.0/46 words correct
 33.03333333333333/46 characters in words correct

In [243]:
test('test')

Proposed: W-E-R-Y-I-L-Y. | Actual: W-R-Y-L-Y. | Matches: NO
Proposed: G-L-I-N-E-S. | Actual: G-L-I-S-T-E-N. | Matches: NO
Proposed: C-A-S-E-L. | Actual: Q-U-E-S-T. | Matches: NO
Proposed: C-E-R-E-A-V-E. | Actual: C-R-A-V-E. | Matches: NO
Proposed: L-U-S-I-N. | Actual: L-U-S-H. | Matches: NO
Proposed: F-A-L-I-C-E. | Actual: F-A-B-L-E. | Matches: NO
Proposed: K-N-A-R-K. | Actual: K-N-A-C-K. | Matches: NO
Proposed: T-I-R-U-M-P-H-I-L-E. | Actual: T-R-I-U-M-P-H. | Matches: NO
Proposed: S-A-P-I-C-R-I-A. | Actual: S-A-P-P-H-I-R-E. | Matches: NO
Proposed: E-X-P-S-T. | Actual: E-X-P-O-S-E. | Matches: NO
Proposed: F-S-R-O-C-S. | Actual: F-R-E-S-C-O-S. | Matches: NO
Proposed: W-I-P-S. | Actual: W-I-S-P. | Matches: NO
Proposed: M-I-R-E-G. | Actual: M-I-R-A-G-E. | Matches: NO
Proposed: I-V-O-R-Y. | Actual: I-V-O-R-Y. | Matches: YES
Proposed: O-N-S-H-E-R-D. | Actual: O-N-S-E-T. | Matches: NO
Proposed: E-L-E-U-A. | Actual: E-L-U-D-E. | Matches: NO
1.0/46 words correct
 10.694642857142854/46 characters in words correct

## A definitive improvement , however looks like huge overfitting